version: "3.8"

services:
  url-shortener-db:
    image: postgres:17-alpine
    container_name: url-shortener-db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"

  url-shortener-redis:
    image: redis:8.0.0-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 100mb
      --maxmemory-policy volatile-lru
      --requirepass redisPasswordLocal
