spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      password: redisPasswordLocal
